-- MySQL Script generated by MySQL Workbench
-- Tue May 21 11:55:27 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_ventas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_ventas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_ventas` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish2_ci ;
USE `bd_ventas` ;

-- -----------------------------------------------------
-- Table `bd_ventas`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_ventas`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `bd_ventas`.`Cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `email` VARCHAR(250) NOT NULL,
  `edad` TINYINT NOT NULL,
  `activo` VARCHAR(45) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idtable1_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_ventas`.`Producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_ventas`.`Producto` ;

CREATE TABLE IF NOT EXISTS `bd_ventas`.`Producto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `cantidad` INT NOT NULL,
  `precio` DECIMAL NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_ventas`.`Compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_ventas`.`Compra` ;

CREATE TABLE IF NOT EXISTS `bd_ventas`.`Compra` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Cliente_id` INT NOT NULL,
  `Producto_id` INT NOT NULL,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `cantidad` INT NOT NULL,
  INDEX `fk_Cliente_has_Producto_Producto1_idx` (`Producto_id` ASC) VISIBLE,
  INDEX `fk_Cliente_has_Producto_Cliente_idx` (`Cliente_id` ASC) VISIBLE,
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE,
  PRIMARY KEY (`Id`),
  CONSTRAINT `fk_Cliente_has_Producto_Cliente`
    FOREIGN KEY (`Cliente_id`)
    REFERENCES `bd_ventas`.`Cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_has_Producto_Producto1`
    FOREIGN KEY (`Producto_id`)
    REFERENCES `bd_ventas`.`Producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `bd_ventas`.`Cliente`
-- -----------------------------------------------------
START TRANSACTION;
USE `bd_ventas`;
INSERT INTO `bd_ventas`.`Cliente` (`id`, `nombre`, `email`, `edad`, `activo`, `password`) VALUES (DEFAULT, 'Prueba', 'prueba@email.com', 20, '0', '1234');

COMMIT;


-- -----------------------------------------------------
-- Data for table `bd_ventas`.`Producto`
-- -----------------------------------------------------
START TRANSACTION;
USE `bd_ventas`;
INSERT INTO `bd_ventas`.`Producto` (`id`, `nombre`, `cantidad`, `precio`) VALUES (DEFAULT, 'ProductoPrueba', 1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `bd_ventas`.`Compra`
-- -----------------------------------------------------
START TRANSACTION;
USE `bd_ventas`;
INSERT INTO `bd_ventas`.`Compra` (`Id`, `Cliente_id`, `Producto_id`, `fecha`, `cantidad`) VALUES (DEFAULT, 1, 1, DEFAULT, 1);

COMMIT;

